### ISSUE TITLE
[Korekto][Daily] Votre note actuelle : 5/11

### ISSUE THREAD

**Issue by korekto-agent** [WarningImHack3r/amqp_training#1]
# Exercice commencé
Votre note est de **5**/11.  

## Détail
* Part 1 - Compilation & Tests: 2/2
* Part 2 - CI: 1/1
* Part 3 - Listener AMQP & Server HTTP: 2/4
    * GET /api/message should respond a list of 3 messages (messages sent), but was: 0

* Part 4 - Client AMQP & message limit: 0/4
    * GET /api/message should respond a list of 2 messages (messages sent), but was: 0
    * GET /api/message should respond a list of the last *10* messages received but returned *0*

*Analyse effectuée à 2021-12-08T23:50:05.711966800Z.*

**Comment by WarningImHack3r** [comment]
Fixed
